# Generated by Django 2.1 on 2023-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=20)),
                ('product', models.CharField(default='', max_length=20)),
                ('model', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default='')),
                ('quantity', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=150)),
                ('bill_number', models.CharField(default='', max_length=20)),
                ('date', models.DateField(default='')),
                ('brand', models.CharField(default='', max_length=50)),
                ('product', models.CharField(default='', max_length=50)),
                ('model', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default='')),
                ('quantity', models.IntegerField(default='')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('brand_name', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20)),
                ('model_Name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
