# Generated by Django 4.2.4 on 2023-08-22 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0002_rename_brand_name_sales_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='model',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='', max_length=50)),
                ('product', models.CharField(default='', max_length=50)),
                ('model', models.CharField(default='', max_length=50)),
                ('price', models.IntegerField(default='')),
                ('quantity', models.IntegerField(default='')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_manager.invoice')),
            ],
        ),
    ]
